In [1]:
! pip install pandas openpyxl seaborn matplotlib

Requirement already satisfied: pandas in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (2.3.3)
Requirement already satisfied: openpyxl in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (3.1.5)
Requirement already satisfied: seaborn in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (3.10.0)
Requirement already satisfied: numpy>=1.23.2 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: et-xmlfile in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\jatin\anaconda3\envs\eda_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('anemia_dataset.csv')
df_cluster = pd.read_csv('clusters.csv')
df_severity = pd.read_csv('severity.csv')

In [13]:
df_cluster

      cluster
0           1
1           2
2           2
3           2
4           2
...       ...
1129        2
1130        0
1131        2
1132        2
1133        0

[1134 rows x 1 columns]

In [4]:
import os
print(os.listdir())

['.git', 'anemia_dataset.csv', 'clusters.csv', 'main.py', 'mappings.ipynb', 'microcytic_severity.ipynb', 'microcytic_severity_Clustering.ipynb', 'pooja_data.csv', 'requirements.txt', 'severity.csv', 'venv']

In [ ]:
print(len(df), len(df_cluster), len(df_severity))
df['cluster'] = df_cluster['cluster']
df['severity'] = df_severity['severity']

1281 1134 1281

In [14]:
df['cluster']

0       1.0
1       2.0
2       2.0
3       2.0
4       2.0
       ...
1276    NaN
1277    NaN
1278    NaN
1279    NaN
1280    NaN
Name: cluster, Length: 1281, dtype: float64

In [12]:
print(df['severity'])

0       6.608886
1       7.090613
2       6.434015
3       7.401842
4       7.097833
          ...
1276    1.401051
1277    0.130322
1278    1.288024
1279    1.499202
1280    0.051945
Name: severity, Length: 1281, dtype: float64

In [15]:
df.sample(12)

,WBC,LYMp,NEUTp,LYMn,NEUTn,RBC,HGB,HCT,MCV,MCH,MCHC,PLT,PDW,PCT,cluster,severity,category
1211,8.94,25.845,77.511,1.88076,5.14094,4.79,12.1,46.1526,85.2,25.3,29.7,265.0,14.312512,0.26028,NaN,3.104876,NaN
51,8.30,24.800,65.900,2.10000,5.40000,4.52,15.1,42.2000,93.5,33.4,35.7,135.0,13.600000,0.12000,2.0,0.368098,Mild
928,6.22,25.845,77.511,1.88076,5.14094,4.81,13.4,46.1526,92.3,27.9,30.2,150.0,14.312512,0.26028,1.0,1.440299,Severe
84,6.00,9.600,83.600,0.60000,5.00000,3.10,10.5,32.7000,105.8,33.8,32.1,77.0,14.900000,0.07000,2.0,3.556211,Mild
74,6.60,15.500,75.900,1.00000,5.00000,4.40,12.6,39.3000,89.5,28.6,32.0,156.0,10.700000,0.13000,1.0,1.792236,Severe
526,7.70,25.845,77.511,1.88076,5.14094,4.60,12.2,46.1526,88.0,29.0,33.0,310.0,13.500000,0.26028,2.0,1.686830,Mild
786,7.80,25.845,77.511,1.88076,5.14094,4.80,12.7,46.1526,86.0,29.0,33.0,290.0,12.700000,0.26028,2.0,1.399705,Mild
1254,4.50,25.845,77.511,1.88076,5.14094,5.11,13.7,46.1526,81.4,26.8,33.0,192.0,14.312512,0.26028,NaN,1.510829,NaN
962,6.40,25.845,77.511,1.88076,5.14094,2.99,6.9,46.1526,77.3,23.1,29.9,187.0,14.312512,0.26028,0.0,8.069128,Normal
352,9.00,24.700,69.000,2.20000,6.20000,5.16,14.3,44.7000,86.7,27.7,31.9,182.0,12.300000,0.16000,2.0,0.997154,Mild
1252,7.10,25.845,77.511,1.88076,5.14094,4.08,12.6,46.1526,95.0,30.8,32.4,183.0,14.312512,0.26028,NaN,1.677296,NaN
1120,13.50,25.845,77.511,1.88076,5.14094,4.33,12.5,46.1526,97.7,28.9,29.6,352.0,14.312512,0.26028,2.0,2.072676,Mild

In [6]:
cluster_summary = df.groupby('cluster')['severity'].mean()
print(cluster_summary)

cluster
0.0    2.280262
1.0    3.298282
2.0    2.984983
Name: severity, dtype: float64

In [7]:
cluster_order = cluster_summary.sort_values().index
print(cluster_order)

Index([0.0, 2.0, 1.0], dtype='float64', name='cluster')

In [8]:
mapping = {
    cluster_order[0]: 'Normal',
    cluster_order[1]: 'Mild',
    cluster_order[2]: 'Severe'
}

df['category'] = df['cluster'].map(mapping)

In [9]:
cluster_summary = df.groupby('cluster')['severity'].mean()
print(cluster_summary)

cluster
0.0    2.280262
1.0    3.298282
2.0    2.984983
Name: severity, dtype: float64

In [10]:
ranges = df.groupby('category')['severity'].quantile([0.1, 0.9]).unstack()
ranges.columns = ['low','high']
print(ranges)

               low      high
category
Mild      0.359666  5.999018
Normal    0.102770  5.079382
Severe    0.551210  6.655498